version: "3.9"
   
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    # environment:
    #   - POSTGRES_NAME=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_HOST=db
    #   - POSTGRES_PORT=5432
    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   volumes:
  #     - ./.local/data/db:/var/lib/postgresql/data
  #   user: 1000:1000
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  db:
    image: postgres
    volumes:
      - ./.local/data/db:/var/lib/postgresql/data
    user: 1000:1000
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
